// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eelqaywqpcawkavieuki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbHFheXdxcGNhd2thdmlldWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NjE5ODQsImV4cCI6MjA1NzIzNzk4NH0.Kc4sClDbhfdDB2wXApM7CwoUVZH3NE7HL_n-eaIOpnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);